// <auto-generated />
namespace Social_Media.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class grouppost1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(grouppost1));
        
        string IMigrationMetadata.Id
        {
            get { return "202006071645309_grouppost1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
